language: python
python:
  - "2.6"
  - "2.7"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq openjdk-6-jdk openjdk-6-jre
 - pip install unittest2
script: python setup.py develop && nosetests
notifications:
  email:
    recipients:
      - pyjava-dev@googlegroups.com
    on_success: change
    on_failure: always
