language: python
python:
  - "2.7"
jdk:
  - openjdk6
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq valgrind
 - pip install unittest2
script: python setup.py develop && valgrind nosetests
